pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - feature_develop
  paths:
    include:
      - src/**
      - Dockerfile
      - package.json

variables:
  dockerimagerepo: 'venkeyboda/netflix'
  dockerImagetag: 'latest'

stages:

# ========================= CI STAGE =========================

- stage: CI
  displayName: "Build & Push Docker Image"
  condition: |
    or(
      contains(variables['Build.SourceVersionMessage'], 'src'),
      contains(variables['Build.SourceVersionMessage'], 'Dockerfile'),
      contains(variables['Build.SourceVersionMessage'], 'package.json')
    )

  jobs:
    - job: build
      displayName: 'Building and testing'

      steps:
        - task: Docker@2
          displayName: 'Build docker image'  
          inputs:
            command: 'build'
            Dockerfile: 'Dockerfile'
            repository: $(dockerimagerepo)
            tags: |
              $(dockerImagetag)
            arguments: |
              --build-arg TMDB_V3_API_KEY=$(TMDB_V3_API_KEY)

        - task: Bash@3
          displayName: 'Trivy Scan'
          inputs:
            filePath: 'Scripts/trivy-scan.sh'
            arguments: '$(dockerimagerepo):$(dockerImagetag)'
            
        - task: Docker@2
          displayName: 'Push docker image'
          inputs:
            command: 'push'
            containerRegistry: 'DOCKER_HUB'
            repository: $(dockerimagerepo)
            tags: |
              $(dockerImagetag)

        - task: PublishBuildArtifacts@1
          displayName: 'Upload Trivy Report'
          inputs:
            PathtoPublish: 'trivy-reports'
            ArtifactName: 'Trivy-Report'
            publishLocation: 'Container'

# ========================= CD STAGE =========================

- stage: CD
  displayName: "Deploy to AKS"
  dependsOn: []
  condition: succeeded()

  jobs:
    - job: Deploy
      displayName: 'Infrastructure + App + Monitoring'
      pool:
        vmImage: 'ubuntu-latest'

      steps:

        - task: CmdLine@2
          displayName: 'Docker Pull'
          inputs:
            script: |
              docker pull $(dockerimagerepo):$(dockerImagetag)

        - task: Bash@3
          displayName: 'Install Terraform'
          inputs:
            targetType: 'filePath'
            filePath: 'Scripts/install-terraform.sh'              

        - task: AzureCLI@2
          displayName: Terraform Init Plan Apply
          inputs:
            azureSubscription: 'azure-service-connection'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |

              cd Infra

              terraform init

              terraform plan \
              -var-file="terraform.tfvars" \
              -input=false \
              -out=tfplan

              terraform apply -auto-approve tfplan
              
              echo "Getting Terraform outputs..."

              CLUSTER_NAME=$(terraform output -raw aks_cluster_name)
              RG_NAME=$(terraform output -raw resource_group_name)

              echo "Cluster Name: $CLUSTER_NAME"
              echo "Resource Group: $RG_NAME"

              az aks get-credentials \
                --resource-group $RG_NAME \
                --name $CLUSTER_NAME \
                --overwrite-existing

        - task: Bash@3
          displayName: 'Deploy Application'
          inputs:
            filePath: 'Scripts/deploy-app.sh'

        - task: Bash@3
          displayName: 'Install Helm'
          inputs:
            filePath: 'Scripts/install-helm.sh'

        - task: Bash@3
          displayName: 'Deploy Monitoring'
          inputs:
            filePath: 'Monitoring/deploy-monitoring.sh'
