apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: venkeyboda/netflix:latest
        resources: 
          limits:
            cpu: 500m
            memory: 256M
          requests:
            cpu: 100m
            memory: 64M
        livenessProbe: 
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe: 
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10            
        ports:
        - containerPort: 80
